name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [self-hosted, react-new-app]

    strategy:
      matrix:
        node-version: [18.15.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.15.0
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: sudo systemctl restart nginx
